language: node_js
sudo: required
node_js:
   - node

before_script:
   - "sudo apt-get update && sudo apt-get install -y nginx make"

script: # the build step
   - sudo make

after_script:
   - sudo make clean
